version: '3.8'

services:
  app:
    build:
      context: .
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    environment:
      - APP_ENV=production
      - APP_KEY=base64:YOUR_APP_KEY
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

  # db:
  #   image: postgres:15
  #   container_name: pg-db
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_DB: laravel
  #     POSTGRES_USER: laravel
  #     POSTGRES_PASSWORD: secret
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata:
