version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aluvimueble
    ports:
      - "8000:80"  # El 80 del contenedor se expone como 8000 en tu máquina
    volumes:
      - .:/var/www/html