version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: aluvi-app:latest
    container_name: laravel_app
    restart: always
    depends_on:
      - db
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_DB=laravel
      - POSTGRES_USER=laravel
      - POSTGRES_PASSWORD=secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
