version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aluvimueble
    ports:
      - "8000:80"  # El 80 del contenedor se expone como 8000 en tu máquina
    volumes:
      - .:/var/www/html
    # depends_on:
    #   - db

  # db:
  #   image: postgres:15
  #   container_name: pg-db
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_DB: laravel
  #     POSTGRES_USER: laravel
  #     POSTGRES_PASSWORD: secret
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata:
