name: Deploy Laravel Application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  # Desplegar cuando se haga un push a la rama master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout Code
        uses: actions/checkout@v4

      # Paso 2: Configurar Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Paso 3: Construir la imagen de Docker
      - name: Build Docker image
        run: |
          docker build -t aluvimueble .

      # Paso 4: Ejecutar el contenedor de Docker
      - name: Run Docker container
        run: |
          docker run -d -p 8000:80 aluvimueble

      - name: Post-deployment check
        run: |
          echo "El contenedor se está ejecutando"
