name: Deploy Laravel Application

on:
  push:
    branches:
      - master  # Desplegar cuando se haga un push a la rama master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout Code
        uses: actions/checkout@v2

      # Paso 2: Configurar Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Paso 3: Construir la imagen de Docker
      - name: Build Docker image
        run: |
          docker build -t mi_app_laravel .

      # Paso 4: Ejecutar el contenedor de Docker
      - name: Run Docker container
        run: |
          docker run -d -p 9000:9000 mi_app_laravel
