name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Asegúrate de que esto coincida con la versión de Node.js de tu proyecto

      - name: Install Dependencies
        run: |
          npm install  # Instala las dependencias de React

      - name: Build React
        run: |
          npm run build  # Construye los archivos estáticos de React

      - name: Set up Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'  # La carpeta pública donde se encuentran los archivos estáticos de React

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

